// SPDX-License-Identifier: Apache-2.0 AND MIT

/*
 * WARNING: do not edit!
 * Generated by crypto/objects/objects.pl
 *
 */

#ifndef OPENSSL_OBJ_MAC_H
# define OPENSSL_OBJ_MAC_H
# pragma once

#define SN_undef                        "UNDEF"
#define LN_undef                        "undefined"
#define NID_undef                       0
#define OBJ_undef                       0L

#define OBJ_csor                2L,16L,840L,1L,101L,3L

#define OBJ_nistAlgorithms              OBJ_csor,4L

#define OBJ_nist_hashalgs               OBJ_nistAlgorithms,2L

#define SN_sha512               "SHA512"
#define LN_sha512               "sha512"
#define NID_sha512              1
#define OBJ_sha512              OBJ_nist_hashalgs,3L

#define SN_frodo640aes          "frodo640aes"
#define LN_frodo640aes          "frodo640aes"
#define NID_frodo640aes         2

#define SN_p256_frodo640aes             "p256_frodo640aes"
#define LN_p256_frodo640aes             "p256_frodo640aes"
#define NID_p256_frodo640aes            3

#define SN_frodo640shake                "frodo640shake"
#define LN_frodo640shake                "frodo640shake"
#define NID_frodo640shake               4

#define SN_p256_frodo640shake           "p256_frodo640shake"
#define LN_p256_frodo640shake           "p256_frodo640shake"
#define NID_p256_frodo640shake          5

#define SN_frodo976aes          "frodo976aes"
#define LN_frodo976aes          "frodo976aes"
#define NID_frodo976aes         6

#define SN_p384_frodo976aes             "p384_frodo976aes"
#define LN_p384_frodo976aes             "p384_frodo976aes"
#define NID_p384_frodo976aes            7

#define SN_frodo976shake                "frodo976shake"
#define LN_frodo976shake                "frodo976shake"
#define NID_frodo976shake               8

#define SN_p384_frodo976shake           "p384_frodo976shake"
#define LN_p384_frodo976shake           "p384_frodo976shake"
#define NID_p384_frodo976shake          9

#define SN_frodo1344aes         "frodo1344aes"
#define LN_frodo1344aes         "frodo1344aes"
#define NID_frodo1344aes                10

#define SN_p521_frodo1344aes            "p521_frodo1344aes"
#define LN_p521_frodo1344aes            "p521_frodo1344aes"
#define NID_p521_frodo1344aes           11

#define SN_frodo1344shake               "frodo1344shake"
#define LN_frodo1344shake               "frodo1344shake"
#define NID_frodo1344shake              12

#define SN_p521_frodo1344shake          "p521_frodo1344shake"
#define LN_p521_frodo1344shake          "p521_frodo1344shake"
#define NID_p521_frodo1344shake         13

#define SN_kyber512             "kyber512"
#define LN_kyber512             "kyber512"
#define NID_kyber512            14

#define SN_p256_kyber512                "p256_kyber512"
#define LN_p256_kyber512                "p256_kyber512"
#define NID_p256_kyber512               15

#define SN_kyber768             "kyber768"
#define LN_kyber768             "kyber768"
#define NID_kyber768            16

#define SN_p384_kyber768                "p384_kyber768"
#define LN_p384_kyber768                "p384_kyber768"
#define NID_p384_kyber768               17

#define SN_kyber1024            "kyber1024"
#define LN_kyber1024            "kyber1024"
#define NID_kyber1024           18

#define SN_p521_kyber1024               "p521_kyber1024"
#define LN_p521_kyber1024               "p521_kyber1024"
#define NID_p521_kyber1024              19

#define SN_ntru_hps2048509              "ntru_hps2048509"
#define LN_ntru_hps2048509              "ntru_hps2048509"
#define NID_ntru_hps2048509             20

#define SN_p256_ntru_hps2048509         "p256_ntru_hps2048509"
#define LN_p256_ntru_hps2048509         "p256_ntru_hps2048509"
#define NID_p256_ntru_hps2048509                21

#define SN_ntru_hps2048677              "ntru_hps2048677"
#define LN_ntru_hps2048677              "ntru_hps2048677"
#define NID_ntru_hps2048677             22

#define SN_p384_ntru_hps2048677         "p384_ntru_hps2048677"
#define LN_p384_ntru_hps2048677         "p384_ntru_hps2048677"
#define NID_p384_ntru_hps2048677                23

#define SN_ntru_hps4096821              "ntru_hps4096821"
#define LN_ntru_hps4096821              "ntru_hps4096821"
#define NID_ntru_hps4096821             24

#define SN_p521_ntru_hps4096821         "p521_ntru_hps4096821"
#define LN_p521_ntru_hps4096821         "p521_ntru_hps4096821"
#define NID_p521_ntru_hps4096821                25

#define SN_ntru_hrss701         "ntru_hrss701"
#define LN_ntru_hrss701         "ntru_hrss701"
#define NID_ntru_hrss701                26

#define SN_p384_ntru_hrss701            "p384_ntru_hrss701"
#define LN_p384_ntru_hrss701            "p384_ntru_hrss701"
#define NID_p384_ntru_hrss701           27

#define SN_lightsaber           "lightsaber"
#define LN_lightsaber           "lightsaber"
#define NID_lightsaber          28

#define SN_p256_lightsaber              "p256_lightsaber"
#define LN_p256_lightsaber              "p256_lightsaber"
#define NID_p256_lightsaber             29

#define SN_saber                "saber"
#define LN_saber                "saber"
#define NID_saber               30

#define SN_p384_saber           "p384_saber"
#define LN_p384_saber           "p384_saber"
#define NID_p384_saber          31

#define SN_firesaber            "firesaber"
#define LN_firesaber            "firesaber"
#define NID_firesaber           32

#define SN_p521_firesaber               "p521_firesaber"
#define LN_p521_firesaber               "p521_firesaber"
#define NID_p521_firesaber              33

#define SN_sidhp434             "sidhp434"
#define LN_sidhp434             "sidhp434"
#define NID_sidhp434            34

#define SN_p256_sidhp434                "p256_sidhp434"
#define LN_p256_sidhp434                "p256_sidhp434"
#define NID_p256_sidhp434               35

#define SN_sidhp503             "sidhp503"
#define LN_sidhp503             "sidhp503"
#define NID_sidhp503            36

#define SN_p256_sidhp503                "p256_sidhp503"
#define LN_p256_sidhp503                "p256_sidhp503"
#define NID_p256_sidhp503               37

#define SN_sidhp610             "sidhp610"
#define LN_sidhp610             "sidhp610"
#define NID_sidhp610            38

#define SN_p384_sidhp610                "p384_sidhp610"
#define LN_p384_sidhp610                "p384_sidhp610"
#define NID_p384_sidhp610               39

#define SN_sidhp751             "sidhp751"
#define LN_sidhp751             "sidhp751"
#define NID_sidhp751            40

#define SN_p521_sidhp751                "p521_sidhp751"
#define LN_p521_sidhp751                "p521_sidhp751"
#define NID_p521_sidhp751               41

#define SN_sikep434             "sikep434"
#define LN_sikep434             "sikep434"
#define NID_sikep434            42

#define SN_p256_sikep434                "p256_sikep434"
#define LN_p256_sikep434                "p256_sikep434"
#define NID_p256_sikep434               43

#define SN_sikep503             "sikep503"
#define LN_sikep503             "sikep503"
#define NID_sikep503            44

#define SN_p256_sikep503                "p256_sikep503"
#define LN_p256_sikep503                "p256_sikep503"
#define NID_p256_sikep503               45

#define SN_sikep610             "sikep610"
#define LN_sikep610             "sikep610"
#define NID_sikep610            46

#define SN_p384_sikep610                "p384_sikep610"
#define LN_p384_sikep610                "p384_sikep610"
#define NID_p384_sikep610               47

#define SN_sikep751             "sikep751"
#define LN_sikep751             "sikep751"
#define NID_sikep751            48

#define SN_p521_sikep751                "p521_sikep751"
#define LN_p521_sikep751                "p521_sikep751"
#define NID_p521_sikep751               49

#define SN_bikel1               "bikel1"
#define LN_bikel1               "bikel1"
#define NID_bikel1              50

#define SN_p256_bikel1          "p256_bikel1"
#define LN_p256_bikel1          "p256_bikel1"
#define NID_p256_bikel1         51

#define SN_bikel3               "bikel3"
#define LN_bikel3               "bikel3"
#define NID_bikel3              52

#define SN_p384_bikel3          "p384_bikel3"
#define LN_p384_bikel3          "p384_bikel3"
#define NID_p384_bikel3         53

#define SN_kyber90s512          "kyber90s512"
#define LN_kyber90s512          "kyber90s512"
#define NID_kyber90s512         54

#define SN_p256_kyber90s512             "p256_kyber90s512"
#define LN_p256_kyber90s512             "p256_kyber90s512"
#define NID_p256_kyber90s512            55

#define SN_kyber90s768          "kyber90s768"
#define LN_kyber90s768          "kyber90s768"
#define NID_kyber90s768         56

#define SN_p384_kyber90s768             "p384_kyber90s768"
#define LN_p384_kyber90s768             "p384_kyber90s768"
#define NID_p384_kyber90s768            57

#define SN_kyber90s1024         "kyber90s1024"
#define LN_kyber90s1024         "kyber90s1024"
#define NID_kyber90s1024                58

#define SN_p521_kyber90s1024            "p521_kyber90s1024"
#define LN_p521_kyber90s1024            "p521_kyber90s1024"
#define NID_p521_kyber90s1024           59

#define SN_hqc128               "hqc128"
#define LN_hqc128               "hqc128"
#define NID_hqc128              60

#define SN_p256_hqc128          "p256_hqc128"
#define LN_p256_hqc128          "p256_hqc128"
#define NID_p256_hqc128         61

#define SN_hqc192               "hqc192"
#define LN_hqc192               "hqc192"
#define NID_hqc192              62

#define SN_p384_hqc192          "p384_hqc192"
#define LN_p384_hqc192          "p384_hqc192"
#define NID_p384_hqc192         63

#define SN_hqc256               "hqc256"
#define LN_hqc256               "hqc256"
#define NID_hqc256              64

#define SN_p521_hqc256          "p521_hqc256"
#define LN_p521_hqc256          "p521_hqc256"
#define NID_p521_hqc256         65

#define SN_ntrulpr653           "ntrulpr653"
#define LN_ntrulpr653           "ntrulpr653"
#define NID_ntrulpr653          66

#define SN_p256_ntrulpr653              "p256_ntrulpr653"
#define LN_p256_ntrulpr653              "p256_ntrulpr653"
#define NID_p256_ntrulpr653             67

#define SN_ntrulpr761           "ntrulpr761"
#define LN_ntrulpr761           "ntrulpr761"
#define NID_ntrulpr761          68

#define SN_p384_ntrulpr761              "p384_ntrulpr761"
#define LN_p384_ntrulpr761              "p384_ntrulpr761"
#define NID_p384_ntrulpr761             69

#define SN_ntrulpr857           "ntrulpr857"
#define LN_ntrulpr857           "ntrulpr857"
#define NID_ntrulpr857          70

#define SN_p384_ntrulpr857              "p384_ntrulpr857"
#define LN_p384_ntrulpr857              "p384_ntrulpr857"
#define NID_p384_ntrulpr857             71

#define SN_sntrup653            "sntrup653"
#define LN_sntrup653            "sntrup653"
#define NID_sntrup653           72

#define SN_p256_sntrup653               "p256_sntrup653"
#define LN_p256_sntrup653               "p256_sntrup653"
#define NID_p256_sntrup653              73

#define SN_sntrup761            "sntrup761"
#define LN_sntrup761            "sntrup761"
#define NID_sntrup761           74

#define SN_p384_sntrup761               "p384_sntrup761"
#define LN_p384_sntrup761               "p384_sntrup761"
#define NID_p384_sntrup761              75

#define SN_sntrup857            "sntrup857"
#define LN_sntrup857            "sntrup857"
#define NID_sntrup857           76

#define SN_p384_sntrup857               "p384_sntrup857"
#define LN_p384_sntrup857               "p384_sntrup857"
#define NID_p384_sntrup857              77

#define SN_dilithium2           "dilithium2"
#define LN_dilithium2           "dilithium2"
#define NID_dilithium2          78
#define OBJ_dilithium2          1L,3L,6L,1L,4L,1L,2L,267L,7L,4L,4L

#define SN_p256_dilithium2              "p256_dilithium2"
#define LN_p256_dilithium2              "p256_dilithium2"
#define NID_p256_dilithium2             79
#define OBJ_p256_dilithium2             1L,3L,9999L,2L,7L,1L

#define SN_rsa3072_dilithium2           "rsa3072_dilithium2"
#define LN_rsa3072_dilithium2           "rsa3072_dilithium2"
#define NID_rsa3072_dilithium2          80
#define OBJ_rsa3072_dilithium2          1L,3L,9999L,2L,7L,2L

#define SN_dilithium3           "dilithium3"
#define LN_dilithium3           "dilithium3"
#define NID_dilithium3          81
#define OBJ_dilithium3          1L,3L,6L,1L,4L,1L,2L,267L,7L,6L,5L

#define SN_p384_dilithium3              "p384_dilithium3"
#define LN_p384_dilithium3              "p384_dilithium3"
#define NID_p384_dilithium3             82
#define OBJ_p384_dilithium3             1L,3L,9999L,2L,7L,3L

#define SN_dilithium5           "dilithium5"
#define LN_dilithium5           "dilithium5"
#define NID_dilithium5          83
#define OBJ_dilithium5          1L,3L,6L,1L,4L,1L,2L,267L,7L,8L,7L

#define SN_p521_dilithium5              "p521_dilithium5"
#define LN_p521_dilithium5              "p521_dilithium5"
#define NID_p521_dilithium5             84
#define OBJ_p521_dilithium5             1L,3L,9999L,2L,7L,4L

#define SN_dilithium2_aes               "dilithium2_aes"
#define LN_dilithium2_aes               "dilithium2_aes"
#define NID_dilithium2_aes              85
#define OBJ_dilithium2_aes              1L,3L,6L,1L,4L,1L,2L,267L,11L,4L,4L

#define SN_p256_dilithium2_aes          "p256_dilithium2_aes"
#define LN_p256_dilithium2_aes          "p256_dilithium2_aes"
#define NID_p256_dilithium2_aes         86
#define OBJ_p256_dilithium2_aes         1L,3L,9999L,2L,11L,1L

#define SN_rsa3072_dilithium2_aes               "rsa3072_dilithium2_aes"
#define LN_rsa3072_dilithium2_aes               "rsa3072_dilithium2_aes"
#define NID_rsa3072_dilithium2_aes              87
#define OBJ_rsa3072_dilithium2_aes              1L,3L,9999L,2L,11L,2L

#define SN_dilithium3_aes               "dilithium3_aes"
#define LN_dilithium3_aes               "dilithium3_aes"
#define NID_dilithium3_aes              88
#define OBJ_dilithium3_aes              1L,3L,6L,1L,4L,1L,2L,267L,11L,6L,5L

#define SN_p384_dilithium3_aes          "p384_dilithium3_aes"
#define LN_p384_dilithium3_aes          "p384_dilithium3_aes"
#define NID_p384_dilithium3_aes         89
#define OBJ_p384_dilithium3_aes         1L,3L,9999L,2L,11L,3L

#define SN_dilithium5_aes               "dilithium5_aes"
#define LN_dilithium5_aes               "dilithium5_aes"
#define NID_dilithium5_aes              90
#define OBJ_dilithium5_aes              1L,3L,6L,1L,4L,1L,2L,267L,11L,8L,7L

#define SN_p521_dilithium5_aes          "p521_dilithium5_aes"
#define LN_p521_dilithium5_aes          "p521_dilithium5_aes"
#define NID_p521_dilithium5_aes         91
#define OBJ_p521_dilithium5_aes         1L,3L,9999L,2L,11L,4L

#define SN_falcon512            "falcon512"
#define LN_falcon512            "falcon512"
#define NID_falcon512           92
#define OBJ_falcon512           1L,3L,9999L,3L,1L

#define SN_p256_falcon512               "p256_falcon512"
#define LN_p256_falcon512               "p256_falcon512"
#define NID_p256_falcon512              93
#define OBJ_p256_falcon512              1L,3L,9999L,3L,2L

#define SN_rsa3072_falcon512            "rsa3072_falcon512"
#define LN_rsa3072_falcon512            "rsa3072_falcon512"
#define NID_rsa3072_falcon512           94
#define OBJ_rsa3072_falcon512           1L,3L,9999L,3L,3L

#define SN_falcon1024           "falcon1024"
#define LN_falcon1024           "falcon1024"
#define NID_falcon1024          95
#define OBJ_falcon1024          1L,3L,9999L,3L,4L

#define SN_p521_falcon1024              "p521_falcon1024"
#define LN_p521_falcon1024              "p521_falcon1024"
#define NID_p521_falcon1024             96
#define OBJ_p521_falcon1024             1L,3L,9999L,3L,5L

#define SN_picnicl1full         "picnicl1full"
#define LN_picnicl1full         "picnicl1full"
#define NID_picnicl1full                97
#define OBJ_picnicl1full                1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,7L

#define SN_p256_picnicl1full            "p256_picnicl1full"
#define LN_p256_picnicl1full            "p256_picnicl1full"
#define NID_p256_picnicl1full           98
#define OBJ_p256_picnicl1full           1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,8L

#define SN_rsa3072_picnicl1full         "rsa3072_picnicl1full"
#define LN_rsa3072_picnicl1full         "rsa3072_picnicl1full"
#define NID_rsa3072_picnicl1full                99
#define OBJ_rsa3072_picnicl1full                1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,9L

#define SN_picnic3l1            "picnic3l1"
#define LN_picnic3l1            "picnic3l1"
#define NID_picnic3l1           100
#define OBJ_picnic3l1           1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,21L

#define SN_p256_picnic3l1               "p256_picnic3l1"
#define LN_p256_picnic3l1               "p256_picnic3l1"
#define NID_p256_picnic3l1              101
#define OBJ_p256_picnic3l1              1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,22L

#define SN_rsa3072_picnic3l1            "rsa3072_picnic3l1"
#define LN_rsa3072_picnic3l1            "rsa3072_picnic3l1"
#define NID_rsa3072_picnic3l1           102
#define OBJ_rsa3072_picnic3l1           1L,3L,6L,1L,4L,1L,311L,89L,2L,1L,23L

#define SN_rainbowIclassic              "rainbowIclassic"
#define LN_rainbowIclassic              "rainbowIclassic"
#define NID_rainbowIclassic             103
#define OBJ_rainbowIclassic             1L,3L,9999L,5L,1L,1L,1L

#define SN_p256_rainbowIclassic         "p256_rainbowIclassic"
#define LN_p256_rainbowIclassic         "p256_rainbowIclassic"
#define NID_p256_rainbowIclassic                104
#define OBJ_p256_rainbowIclassic                1L,3L,9999L,5L,1L,2L,1L

#define SN_rsa3072_rainbowIclassic              "rsa3072_rainbowIclassic"
#define LN_rsa3072_rainbowIclassic              "rsa3072_rainbowIclassic"
#define NID_rsa3072_rainbowIclassic             105
#define OBJ_rsa3072_rainbowIclassic             1L,3L,9999L,5L,1L,3L,1L

#define SN_rainbowVclassic              "rainbowVclassic"
#define LN_rainbowVclassic              "rainbowVclassic"
#define NID_rainbowVclassic             106
#define OBJ_rainbowVclassic             1L,3L,9999L,5L,3L,1L,1L

#define SN_p521_rainbowVclassic         "p521_rainbowVclassic"
#define LN_p521_rainbowVclassic         "p521_rainbowVclassic"
#define NID_p521_rainbowVclassic                107
#define OBJ_p521_rainbowVclassic                1L,3L,9999L,5L,3L,2L,1L

#define SN_sphincsharaka128frobust              "sphincsharaka128frobust"
#define LN_sphincsharaka128frobust              "sphincsharaka128frobust"
#define NID_sphincsharaka128frobust             108
#define OBJ_sphincsharaka128frobust             1L,3L,9999L,6L,1L,1L

#define SN_p256_sphincsharaka128frobust         "p256_sphincsharaka128frobust"
#define LN_p256_sphincsharaka128frobust         "p256_sphincsharaka128frobust"
#define NID_p256_sphincsharaka128frobust                109
#define OBJ_p256_sphincsharaka128frobust                1L,3L,9999L,6L,1L,2L

#define SN_rsa3072_sphincsharaka128frobust              "rsa3072_sphincsharaka128frobust"
#define LN_rsa3072_sphincsharaka128frobust              "rsa3072_sphincsharaka128frobust"
#define NID_rsa3072_sphincsharaka128frobust             110
#define OBJ_rsa3072_sphincsharaka128frobust             1L,3L,9999L,6L,1L,3L

#define SN_sphincssha256128frobust              "sphincssha256128frobust"
#define LN_sphincssha256128frobust              "sphincssha256128frobust"
#define NID_sphincssha256128frobust             111
#define OBJ_sphincssha256128frobust             1L,3L,9999L,6L,4L,1L

#define SN_p256_sphincssha256128frobust         "p256_sphincssha256128frobust"
#define LN_p256_sphincssha256128frobust         "p256_sphincssha256128frobust"
#define NID_p256_sphincssha256128frobust                112
#define OBJ_p256_sphincssha256128frobust                1L,3L,9999L,6L,4L,2L

#define SN_rsa3072_sphincssha256128frobust              "rsa3072_sphincssha256128frobust"
#define LN_rsa3072_sphincssha256128frobust              "rsa3072_sphincssha256128frobust"
#define NID_rsa3072_sphincssha256128frobust             113
#define OBJ_rsa3072_sphincssha256128frobust             1L,3L,9999L,6L,4L,3L

#define SN_sphincsshake256128frobust            "sphincsshake256128frobust"
#define LN_sphincsshake256128frobust            "sphincsshake256128frobust"
#define NID_sphincsshake256128frobust           114
#define OBJ_sphincsshake256128frobust           1L,3L,9999L,6L,7L,1L

#define SN_p256_sphincsshake256128frobust               "p256_sphincsshake256128frobust"
#define LN_p256_sphincsshake256128frobust               "p256_sphincsshake256128frobust"
#define NID_p256_sphincsshake256128frobust              115
#define OBJ_p256_sphincsshake256128frobust              1L,3L,9999L,6L,7L,2L

#define SN_rsa3072_sphincsshake256128frobust            "rsa3072_sphincsshake256128frobust"
#define LN_rsa3072_sphincsshake256128frobust            "rsa3072_sphincsshake256128frobust"
#define NID_rsa3072_sphincsshake256128frobust           116
#define OBJ_rsa3072_sphincsshake256128frobust           1L,3L,9999L,6L,7L,3L

#endif /* OPENSSL_OBJ_MAC_H */
