// SPDX-License-Identifier: Apache-2.0 AND MIT

/*
 * WARNING: do not edit!
 * Generated by crypto/objects/obj_dat.pl
 *
 */

/* Serialized OID's */
static const unsigned char so[304] = {
    0x60,0x86,0x48,0x01,0x65,0x03,0x04,0x02,0x03,  /* [    0] OBJ_sha512 */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x07,0x04,0x04,  /* [    9] OBJ_dilithium2 */
    0x2B,0xCE,0x0F,0x02,0x07,0x01,                 /* [   20] OBJ_p256_dilithium2 */
    0x2B,0xCE,0x0F,0x02,0x07,0x02,                 /* [   26] OBJ_rsa3072_dilithium2 */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x07,0x06,0x05,  /* [   32] OBJ_dilithium3 */
    0x2B,0xCE,0x0F,0x02,0x07,0x03,                 /* [   43] OBJ_p384_dilithium3 */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x07,0x08,0x07,  /* [   49] OBJ_dilithium5 */
    0x2B,0xCE,0x0F,0x02,0x07,0x04,                 /* [   60] OBJ_p521_dilithium5 */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x0B,0x04,0x04,  /* [   66] OBJ_dilithium2_aes */
    0x2B,0xCE,0x0F,0x02,0x0B,0x01,                 /* [   77] OBJ_p256_dilithium2_aes */
    0x2B,0xCE,0x0F,0x02,0x0B,0x02,                 /* [   83] OBJ_rsa3072_dilithium2_aes */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x0B,0x06,0x05,  /* [   89] OBJ_dilithium3_aes */
    0x2B,0xCE,0x0F,0x02,0x0B,0x03,                 /* [  100] OBJ_p384_dilithium3_aes */
    0x2B,0x06,0x01,0x04,0x01,0x02,0x82,0x0B,0x0B,0x08,0x07,  /* [  106] OBJ_dilithium5_aes */
    0x2B,0xCE,0x0F,0x02,0x0B,0x04,                 /* [  117] OBJ_p521_dilithium5_aes */
    0x2B,0xCE,0x0F,0x03,0x01,                      /* [  123] OBJ_falcon512 */
    0x2B,0xCE,0x0F,0x03,0x02,                      /* [  128] OBJ_p256_falcon512 */
    0x2B,0xCE,0x0F,0x03,0x03,                      /* [  133] OBJ_rsa3072_falcon512 */
    0x2B,0xCE,0x0F,0x03,0x04,                      /* [  138] OBJ_falcon1024 */
    0x2B,0xCE,0x0F,0x03,0x05,                      /* [  143] OBJ_p521_falcon1024 */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x07,  /* [  148] OBJ_picnicl1full */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x08,  /* [  159] OBJ_p256_picnicl1full */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x09,  /* [  170] OBJ_rsa3072_picnicl1full */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x15,  /* [  181] OBJ_picnic3l1 */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x16,  /* [  192] OBJ_p256_picnic3l1 */
    0x2B,0x06,0x01,0x04,0x01,0x82,0x37,0x59,0x02,0x01,0x17,  /* [  203] OBJ_rsa3072_picnic3l1 */
    0x2B,0xCE,0x0F,0x05,0x01,0x01,0x01,            /* [  214] OBJ_rainbowIclassic */
    0x2B,0xCE,0x0F,0x05,0x01,0x02,0x01,            /* [  221] OBJ_p256_rainbowIclassic */
    0x2B,0xCE,0x0F,0x05,0x01,0x03,0x01,            /* [  228] OBJ_rsa3072_rainbowIclassic */
    0x2B,0xCE,0x0F,0x05,0x03,0x01,0x01,            /* [  235] OBJ_rainbowVclassic */
    0x2B,0xCE,0x0F,0x05,0x03,0x02,0x01,            /* [  242] OBJ_p521_rainbowVclassic */
    0x2B,0xCE,0x0F,0x06,0x01,0x01,                 /* [  249] OBJ_sphincsharaka128frobust */
    0x2B,0xCE,0x0F,0x06,0x01,0x02,                 /* [  255] OBJ_p256_sphincsharaka128frobust */
    0x2B,0xCE,0x0F,0x06,0x01,0x03,                 /* [  261] OBJ_rsa3072_sphincsharaka128frobust */
    0x2B,0xCE,0x0F,0x06,0x04,0x01,                 /* [  267] OBJ_sphincssha256128frobust */
    0x2B,0xCE,0x0F,0x06,0x04,0x02,                 /* [  273] OBJ_p256_sphincssha256128frobust */
    0x2B,0xCE,0x0F,0x06,0x04,0x03,                 /* [  279] OBJ_rsa3072_sphincssha256128frobust */
    0x2B,0xCE,0x0F,0x06,0x07,0x01,                 /* [  285] OBJ_sphincsshake256128frobust */
    0x2B,0xCE,0x0F,0x06,0x07,0x02,                 /* [  291] OBJ_p256_sphincsshake256128frobust */
    0x2B,0xCE,0x0F,0x06,0x07,0x03,                 /* [  297] OBJ_rsa3072_sphincsshake256128frobust */
};

#define NUM_NID 117
static const ASN1_OBJECT nid_objs[NUM_NID] = {
    {"UNDEF", "undefined", NID_undef},
    {"SHA512", "sha512", NID_sha512, 9, &so[0]},
    {"frodo640aes", "frodo640aes", NID_frodo640aes},
    {"p256_frodo640aes", "p256_frodo640aes", NID_p256_frodo640aes},
    {"frodo640shake", "frodo640shake", NID_frodo640shake},
    {"p256_frodo640shake", "p256_frodo640shake", NID_p256_frodo640shake},
    {"frodo976aes", "frodo976aes", NID_frodo976aes},
    {"p384_frodo976aes", "p384_frodo976aes", NID_p384_frodo976aes},
    {"frodo976shake", "frodo976shake", NID_frodo976shake},
    {"p384_frodo976shake", "p384_frodo976shake", NID_p384_frodo976shake},
    {"frodo1344aes", "frodo1344aes", NID_frodo1344aes},
    {"p521_frodo1344aes", "p521_frodo1344aes", NID_p521_frodo1344aes},
    {"frodo1344shake", "frodo1344shake", NID_frodo1344shake},
    {"p521_frodo1344shake", "p521_frodo1344shake", NID_p521_frodo1344shake},
    {"kyber512", "kyber512", NID_kyber512},
    {"p256_kyber512", "p256_kyber512", NID_p256_kyber512},
    {"kyber768", "kyber768", NID_kyber768},
    {"p384_kyber768", "p384_kyber768", NID_p384_kyber768},
    {"kyber1024", "kyber1024", NID_kyber1024},
    {"p521_kyber1024", "p521_kyber1024", NID_p521_kyber1024},
    {"ntru_hps2048509", "ntru_hps2048509", NID_ntru_hps2048509},
    {"p256_ntru_hps2048509", "p256_ntru_hps2048509", NID_p256_ntru_hps2048509},
    {"ntru_hps2048677", "ntru_hps2048677", NID_ntru_hps2048677},
    {"p384_ntru_hps2048677", "p384_ntru_hps2048677", NID_p384_ntru_hps2048677},
    {"ntru_hps4096821", "ntru_hps4096821", NID_ntru_hps4096821},
    {"p521_ntru_hps4096821", "p521_ntru_hps4096821", NID_p521_ntru_hps4096821},
    {"ntru_hrss701", "ntru_hrss701", NID_ntru_hrss701},
    {"p384_ntru_hrss701", "p384_ntru_hrss701", NID_p384_ntru_hrss701},
    {"lightsaber", "lightsaber", NID_lightsaber},
    {"p256_lightsaber", "p256_lightsaber", NID_p256_lightsaber},
    {"saber", "saber", NID_saber},
    {"p384_saber", "p384_saber", NID_p384_saber},
    {"firesaber", "firesaber", NID_firesaber},
    {"p521_firesaber", "p521_firesaber", NID_p521_firesaber},
    {"sidhp434", "sidhp434", NID_sidhp434},
    {"p256_sidhp434", "p256_sidhp434", NID_p256_sidhp434},
    {"sidhp503", "sidhp503", NID_sidhp503},
    {"p256_sidhp503", "p256_sidhp503", NID_p256_sidhp503},
    {"sidhp610", "sidhp610", NID_sidhp610},
    {"p384_sidhp610", "p384_sidhp610", NID_p384_sidhp610},
    {"sidhp751", "sidhp751", NID_sidhp751},
    {"p521_sidhp751", "p521_sidhp751", NID_p521_sidhp751},
    {"sikep434", "sikep434", NID_sikep434},
    {"p256_sikep434", "p256_sikep434", NID_p256_sikep434},
    {"sikep503", "sikep503", NID_sikep503},
    {"p256_sikep503", "p256_sikep503", NID_p256_sikep503},
    {"sikep610", "sikep610", NID_sikep610},
    {"p384_sikep610", "p384_sikep610", NID_p384_sikep610},
    {"sikep751", "sikep751", NID_sikep751},
    {"p521_sikep751", "p521_sikep751", NID_p521_sikep751},
    {"bikel1", "bikel1", NID_bikel1},
    {"p256_bikel1", "p256_bikel1", NID_p256_bikel1},
    {"bikel3", "bikel3", NID_bikel3},
    {"p384_bikel3", "p384_bikel3", NID_p384_bikel3},
    {"kyber90s512", "kyber90s512", NID_kyber90s512},
    {"p256_kyber90s512", "p256_kyber90s512", NID_p256_kyber90s512},
    {"kyber90s768", "kyber90s768", NID_kyber90s768},
    {"p384_kyber90s768", "p384_kyber90s768", NID_p384_kyber90s768},
    {"kyber90s1024", "kyber90s1024", NID_kyber90s1024},
    {"p521_kyber90s1024", "p521_kyber90s1024", NID_p521_kyber90s1024},
    {"hqc128", "hqc128", NID_hqc128},
    {"p256_hqc128", "p256_hqc128", NID_p256_hqc128},
    {"hqc192", "hqc192", NID_hqc192},
    {"p384_hqc192", "p384_hqc192", NID_p384_hqc192},
    {"hqc256", "hqc256", NID_hqc256},
    {"p521_hqc256", "p521_hqc256", NID_p521_hqc256},
    {"ntrulpr653", "ntrulpr653", NID_ntrulpr653},
    {"p256_ntrulpr653", "p256_ntrulpr653", NID_p256_ntrulpr653},
    {"ntrulpr761", "ntrulpr761", NID_ntrulpr761},
    {"p384_ntrulpr761", "p384_ntrulpr761", NID_p384_ntrulpr761},
    {"ntrulpr857", "ntrulpr857", NID_ntrulpr857},
    {"p384_ntrulpr857", "p384_ntrulpr857", NID_p384_ntrulpr857},
    {"sntrup653", "sntrup653", NID_sntrup653},
    {"p256_sntrup653", "p256_sntrup653", NID_p256_sntrup653},
    {"sntrup761", "sntrup761", NID_sntrup761},
    {"p384_sntrup761", "p384_sntrup761", NID_p384_sntrup761},
    {"sntrup857", "sntrup857", NID_sntrup857},
    {"p384_sntrup857", "p384_sntrup857", NID_p384_sntrup857},
    {"dilithium2", "dilithium2", NID_dilithium2, 11, &so[9]},
    {"p256_dilithium2", "p256_dilithium2", NID_p256_dilithium2, 6, &so[20]},
    {"rsa3072_dilithium2", "rsa3072_dilithium2", NID_rsa3072_dilithium2, 6, &so[26]},
    {"dilithium3", "dilithium3", NID_dilithium3, 11, &so[32]},
    {"p384_dilithium3", "p384_dilithium3", NID_p384_dilithium3, 6, &so[43]},
    {"dilithium5", "dilithium5", NID_dilithium5, 11, &so[49]},
    {"p521_dilithium5", "p521_dilithium5", NID_p521_dilithium5, 6, &so[60]},
    {"dilithium2_aes", "dilithium2_aes", NID_dilithium2_aes, 11, &so[66]},
    {"p256_dilithium2_aes", "p256_dilithium2_aes", NID_p256_dilithium2_aes, 6, &so[77]},
    {"rsa3072_dilithium2_aes", "rsa3072_dilithium2_aes", NID_rsa3072_dilithium2_aes, 6, &so[83]},
    {"dilithium3_aes", "dilithium3_aes", NID_dilithium3_aes, 11, &so[89]},
    {"p384_dilithium3_aes", "p384_dilithium3_aes", NID_p384_dilithium3_aes, 6, &so[100]},
    {"dilithium5_aes", "dilithium5_aes", NID_dilithium5_aes, 11, &so[106]},
    {"p521_dilithium5_aes", "p521_dilithium5_aes", NID_p521_dilithium5_aes, 6, &so[117]},
    {"falcon512", "falcon512", NID_falcon512, 5, &so[123]},
    {"p256_falcon512", "p256_falcon512", NID_p256_falcon512, 5, &so[128]},
    {"rsa3072_falcon512", "rsa3072_falcon512", NID_rsa3072_falcon512, 5, &so[133]},
    {"falcon1024", "falcon1024", NID_falcon1024, 5, &so[138]},
    {"p521_falcon1024", "p521_falcon1024", NID_p521_falcon1024, 5, &so[143]},
    {"picnicl1full", "picnicl1full", NID_picnicl1full, 11, &so[148]},
    {"p256_picnicl1full", "p256_picnicl1full", NID_p256_picnicl1full, 11, &so[159]},
    {"rsa3072_picnicl1full", "rsa3072_picnicl1full", NID_rsa3072_picnicl1full, 11, &so[170]},
    {"picnic3l1", "picnic3l1", NID_picnic3l1, 11, &so[181]},
    {"p256_picnic3l1", "p256_picnic3l1", NID_p256_picnic3l1, 11, &so[192]},
    {"rsa3072_picnic3l1", "rsa3072_picnic3l1", NID_rsa3072_picnic3l1, 11, &so[203]},
    {"rainbowIclassic", "rainbowIclassic", NID_rainbowIclassic, 7, &so[214]},
    {"p256_rainbowIclassic", "p256_rainbowIclassic", NID_p256_rainbowIclassic, 7, &so[221]},
    {"rsa3072_rainbowIclassic", "rsa3072_rainbowIclassic", NID_rsa3072_rainbowIclassic, 7, &so[228]},
    {"rainbowVclassic", "rainbowVclassic", NID_rainbowVclassic, 7, &so[235]},
    {"p521_rainbowVclassic", "p521_rainbowVclassic", NID_p521_rainbowVclassic, 7, &so[242]},
    {"sphincsharaka128frobust", "sphincsharaka128frobust", NID_sphincsharaka128frobust, 6, &so[249]},
    {"p256_sphincsharaka128frobust", "p256_sphincsharaka128frobust", NID_p256_sphincsharaka128frobust, 6, &so[255]},
    {"rsa3072_sphincsharaka128frobust", "rsa3072_sphincsharaka128frobust", NID_rsa3072_sphincsharaka128frobust, 6, &so[261]},
    {"sphincssha256128frobust", "sphincssha256128frobust", NID_sphincssha256128frobust, 6, &so[267]},
    {"p256_sphincssha256128frobust", "p256_sphincssha256128frobust", NID_p256_sphincssha256128frobust, 6, &so[273]},
    {"rsa3072_sphincssha256128frobust", "rsa3072_sphincssha256128frobust", NID_rsa3072_sphincssha256128frobust, 6, &so[279]},
    {"sphincsshake256128frobust", "sphincsshake256128frobust", NID_sphincsshake256128frobust, 6, &so[285]},
    {"p256_sphincsshake256128frobust", "p256_sphincsshake256128frobust", NID_p256_sphincsshake256128frobust, 6, &so[291]},
    {"rsa3072_sphincsshake256128frobust", "rsa3072_sphincsshake256128frobust", NID_rsa3072_sphincsshake256128frobust, 6, &so[297]},
};

#define NUM_SN 117
static const unsigned int sn_objs[NUM_SN] = {
       1,    /* "SHA512" */
       0,    /* "UNDEF" */
      50,    /* "bikel1" */
      52,    /* "bikel3" */
      78,    /* "dilithium2" */
      85,    /* "dilithium2_aes" */
      81,    /* "dilithium3" */
      88,    /* "dilithium3_aes" */
      83,    /* "dilithium5" */
      90,    /* "dilithium5_aes" */
      95,    /* "falcon1024" */
      92,    /* "falcon512" */
      32,    /* "firesaber" */
      10,    /* "frodo1344aes" */
      12,    /* "frodo1344shake" */
       2,    /* "frodo640aes" */
       4,    /* "frodo640shake" */
       6,    /* "frodo976aes" */
       8,    /* "frodo976shake" */
      60,    /* "hqc128" */
      62,    /* "hqc192" */
      64,    /* "hqc256" */
      18,    /* "kyber1024" */
      14,    /* "kyber512" */
      16,    /* "kyber768" */
      58,    /* "kyber90s1024" */
      54,    /* "kyber90s512" */
      56,    /* "kyber90s768" */
      28,    /* "lightsaber" */
      20,    /* "ntru_hps2048509" */
      22,    /* "ntru_hps2048677" */
      24,    /* "ntru_hps4096821" */
      26,    /* "ntru_hrss701" */
      66,    /* "ntrulpr653" */
      68,    /* "ntrulpr761" */
      70,    /* "ntrulpr857" */
      51,    /* "p256_bikel1" */
      79,    /* "p256_dilithium2" */
      86,    /* "p256_dilithium2_aes" */
      93,    /* "p256_falcon512" */
       3,    /* "p256_frodo640aes" */
       5,    /* "p256_frodo640shake" */
      61,    /* "p256_hqc128" */
      15,    /* "p256_kyber512" */
      55,    /* "p256_kyber90s512" */
      29,    /* "p256_lightsaber" */
      21,    /* "p256_ntru_hps2048509" */
      67,    /* "p256_ntrulpr653" */
     101,    /* "p256_picnic3l1" */
      98,    /* "p256_picnicl1full" */
     104,    /* "p256_rainbowIclassic" */
      35,    /* "p256_sidhp434" */
      37,    /* "p256_sidhp503" */
      43,    /* "p256_sikep434" */
      45,    /* "p256_sikep503" */
      73,    /* "p256_sntrup653" */
     109,    /* "p256_sphincsharaka128frobust" */
     112,    /* "p256_sphincssha256128frobust" */
     115,    /* "p256_sphincsshake256128frobust" */
      53,    /* "p384_bikel3" */
      82,    /* "p384_dilithium3" */
      89,    /* "p384_dilithium3_aes" */
       7,    /* "p384_frodo976aes" */
       9,    /* "p384_frodo976shake" */
      63,    /* "p384_hqc192" */
      17,    /* "p384_kyber768" */
      57,    /* "p384_kyber90s768" */
      23,    /* "p384_ntru_hps2048677" */
      27,    /* "p384_ntru_hrss701" */
      69,    /* "p384_ntrulpr761" */
      71,    /* "p384_ntrulpr857" */
      31,    /* "p384_saber" */
      39,    /* "p384_sidhp610" */
      47,    /* "p384_sikep610" */
      75,    /* "p384_sntrup761" */
      77,    /* "p384_sntrup857" */
      84,    /* "p521_dilithium5" */
      91,    /* "p521_dilithium5_aes" */
      96,    /* "p521_falcon1024" */
      33,    /* "p521_firesaber" */
      11,    /* "p521_frodo1344aes" */
      13,    /* "p521_frodo1344shake" */
      65,    /* "p521_hqc256" */
      19,    /* "p521_kyber1024" */
      59,    /* "p521_kyber90s1024" */
      25,    /* "p521_ntru_hps4096821" */
     107,    /* "p521_rainbowVclassic" */
      41,    /* "p521_sidhp751" */
      49,    /* "p521_sikep751" */
     100,    /* "picnic3l1" */
      97,    /* "picnicl1full" */
     103,    /* "rainbowIclassic" */
     106,    /* "rainbowVclassic" */
      80,    /* "rsa3072_dilithium2" */
      87,    /* "rsa3072_dilithium2_aes" */
      94,    /* "rsa3072_falcon512" */
     102,    /* "rsa3072_picnic3l1" */
      99,    /* "rsa3072_picnicl1full" */
     105,    /* "rsa3072_rainbowIclassic" */
     110,    /* "rsa3072_sphincsharaka128frobust" */
     113,    /* "rsa3072_sphincssha256128frobust" */
     116,    /* "rsa3072_sphincsshake256128frobust" */
      30,    /* "saber" */
      34,    /* "sidhp434" */
      36,    /* "sidhp503" */
      38,    /* "sidhp610" */
      40,    /* "sidhp751" */
      42,    /* "sikep434" */
      44,    /* "sikep503" */
      46,    /* "sikep610" */
      48,    /* "sikep751" */
      72,    /* "sntrup653" */
      74,    /* "sntrup761" */
      76,    /* "sntrup857" */
     108,    /* "sphincsharaka128frobust" */
     111,    /* "sphincssha256128frobust" */
     114,    /* "sphincsshake256128frobust" */
};

#define NUM_LN 117
static const unsigned int ln_objs[NUM_LN] = {
      50,    /* "bikel1" */
      52,    /* "bikel3" */
      78,    /* "dilithium2" */
      85,    /* "dilithium2_aes" */
      81,    /* "dilithium3" */
      88,    /* "dilithium3_aes" */
      83,    /* "dilithium5" */
      90,    /* "dilithium5_aes" */
      95,    /* "falcon1024" */
      92,    /* "falcon512" */
      32,    /* "firesaber" */
      10,    /* "frodo1344aes" */
      12,    /* "frodo1344shake" */
       2,    /* "frodo640aes" */
       4,    /* "frodo640shake" */
       6,    /* "frodo976aes" */
       8,    /* "frodo976shake" */
      60,    /* "hqc128" */
      62,    /* "hqc192" */
      64,    /* "hqc256" */
      18,    /* "kyber1024" */
      14,    /* "kyber512" */
      16,    /* "kyber768" */
      58,    /* "kyber90s1024" */
      54,    /* "kyber90s512" */
      56,    /* "kyber90s768" */
      28,    /* "lightsaber" */
      20,    /* "ntru_hps2048509" */
      22,    /* "ntru_hps2048677" */
      24,    /* "ntru_hps4096821" */
      26,    /* "ntru_hrss701" */
      66,    /* "ntrulpr653" */
      68,    /* "ntrulpr761" */
      70,    /* "ntrulpr857" */
      51,    /* "p256_bikel1" */
      79,    /* "p256_dilithium2" */
      86,    /* "p256_dilithium2_aes" */
      93,    /* "p256_falcon512" */
       3,    /* "p256_frodo640aes" */
       5,    /* "p256_frodo640shake" */
      61,    /* "p256_hqc128" */
      15,    /* "p256_kyber512" */
      55,    /* "p256_kyber90s512" */
      29,    /* "p256_lightsaber" */
      21,    /* "p256_ntru_hps2048509" */
      67,    /* "p256_ntrulpr653" */
     101,    /* "p256_picnic3l1" */
      98,    /* "p256_picnicl1full" */
     104,    /* "p256_rainbowIclassic" */
      35,    /* "p256_sidhp434" */
      37,    /* "p256_sidhp503" */
      43,    /* "p256_sikep434" */
      45,    /* "p256_sikep503" */
      73,    /* "p256_sntrup653" */
     109,    /* "p256_sphincsharaka128frobust" */
     112,    /* "p256_sphincssha256128frobust" */
     115,    /* "p256_sphincsshake256128frobust" */
      53,    /* "p384_bikel3" */
      82,    /* "p384_dilithium3" */
      89,    /* "p384_dilithium3_aes" */
       7,    /* "p384_frodo976aes" */
       9,    /* "p384_frodo976shake" */
      63,    /* "p384_hqc192" */
      17,    /* "p384_kyber768" */
      57,    /* "p384_kyber90s768" */
      23,    /* "p384_ntru_hps2048677" */
      27,    /* "p384_ntru_hrss701" */
      69,    /* "p384_ntrulpr761" */
      71,    /* "p384_ntrulpr857" */
      31,    /* "p384_saber" */
      39,    /* "p384_sidhp610" */
      47,    /* "p384_sikep610" */
      75,    /* "p384_sntrup761" */
      77,    /* "p384_sntrup857" */
      84,    /* "p521_dilithium5" */
      91,    /* "p521_dilithium5_aes" */
      96,    /* "p521_falcon1024" */
      33,    /* "p521_firesaber" */
      11,    /* "p521_frodo1344aes" */
      13,    /* "p521_frodo1344shake" */
      65,    /* "p521_hqc256" */
      19,    /* "p521_kyber1024" */
      59,    /* "p521_kyber90s1024" */
      25,    /* "p521_ntru_hps4096821" */
     107,    /* "p521_rainbowVclassic" */
      41,    /* "p521_sidhp751" */
      49,    /* "p521_sikep751" */
     100,    /* "picnic3l1" */
      97,    /* "picnicl1full" */
     103,    /* "rainbowIclassic" */
     106,    /* "rainbowVclassic" */
      80,    /* "rsa3072_dilithium2" */
      87,    /* "rsa3072_dilithium2_aes" */
      94,    /* "rsa3072_falcon512" */
     102,    /* "rsa3072_picnic3l1" */
      99,    /* "rsa3072_picnicl1full" */
     105,    /* "rsa3072_rainbowIclassic" */
     110,    /* "rsa3072_sphincsharaka128frobust" */
     113,    /* "rsa3072_sphincssha256128frobust" */
     116,    /* "rsa3072_sphincsshake256128frobust" */
      30,    /* "saber" */
       1,    /* "sha512" */
      34,    /* "sidhp434" */
      36,    /* "sidhp503" */
      38,    /* "sidhp610" */
      40,    /* "sidhp751" */
      42,    /* "sikep434" */
      44,    /* "sikep503" */
      46,    /* "sikep610" */
      48,    /* "sikep751" */
      72,    /* "sntrup653" */
      74,    /* "sntrup761" */
      76,    /* "sntrup857" */
     108,    /* "sphincsharaka128frobust" */
     111,    /* "sphincssha256128frobust" */
     114,    /* "sphincsshake256128frobust" */
       0,    /* "undefined" */
};

#define NUM_OBJ 41
static const unsigned int obj_objs[NUM_OBJ] = {
       0,    /* OBJ_undef                        0 */
      92,    /* OBJ_falcon512                    1 3 9999 3 1 */
      93,    /* OBJ_p256_falcon512               1 3 9999 3 2 */
      94,    /* OBJ_rsa3072_falcon512            1 3 9999 3 3 */
      95,    /* OBJ_falcon1024                   1 3 9999 3 4 */
      96,    /* OBJ_p521_falcon1024              1 3 9999 3 5 */
      79,    /* OBJ_p256_dilithium2              1 3 9999 2 7 1 */
      80,    /* OBJ_rsa3072_dilithium2           1 3 9999 2 7 2 */
      82,    /* OBJ_p384_dilithium3              1 3 9999 2 7 3 */
      84,    /* OBJ_p521_dilithium5              1 3 9999 2 7 4 */
      86,    /* OBJ_p256_dilithium2_aes          1 3 9999 2 11 1 */
      87,    /* OBJ_rsa3072_dilithium2_aes       1 3 9999 2 11 2 */
      89,    /* OBJ_p384_dilithium3_aes          1 3 9999 2 11 3 */
      91,    /* OBJ_p521_dilithium5_aes          1 3 9999 2 11 4 */
     108,    /* OBJ_sphincsharaka128frobust      1 3 9999 6 1 1 */
     109,    /* OBJ_p256_sphincsharaka128frobust 1 3 9999 6 1 2 */
     110,    /* OBJ_rsa3072_sphincsharaka128frobust 1 3 9999 6 1 3 */
     111,    /* OBJ_sphincssha256128frobust      1 3 9999 6 4 1 */
     112,    /* OBJ_p256_sphincssha256128frobust 1 3 9999 6 4 2 */
     113,    /* OBJ_rsa3072_sphincssha256128frobust 1 3 9999 6 4 3 */
     114,    /* OBJ_sphincsshake256128frobust    1 3 9999 6 7 1 */
     115,    /* OBJ_p256_sphincsshake256128frobust 1 3 9999 6 7 2 */
     116,    /* OBJ_rsa3072_sphincsshake256128frobust 1 3 9999 6 7 3 */
     103,    /* OBJ_rainbowIclassic              1 3 9999 5 1 1 1 */
     104,    /* OBJ_p256_rainbowIclassic         1 3 9999 5 1 2 1 */
     105,    /* OBJ_rsa3072_rainbowIclassic      1 3 9999 5 1 3 1 */
     106,    /* OBJ_rainbowVclassic              1 3 9999 5 3 1 1 */
     107,    /* OBJ_p521_rainbowVclassic         1 3 9999 5 3 2 1 */
       1,    /* OBJ_sha512                       2 16 840 1 101 3 4 2 3 */
      78,    /* OBJ_dilithium2                   1 3 6 1 4 1 2 267 7 4 4 */
      81,    /* OBJ_dilithium3                   1 3 6 1 4 1 2 267 7 6 5 */
      83,    /* OBJ_dilithium5                   1 3 6 1 4 1 2 267 7 8 7 */
      85,    /* OBJ_dilithium2_aes               1 3 6 1 4 1 2 267 11 4 4 */
      88,    /* OBJ_dilithium3_aes               1 3 6 1 4 1 2 267 11 6 5 */
      90,    /* OBJ_dilithium5_aes               1 3 6 1 4 1 2 267 11 8 7 */
      97,    /* OBJ_picnicl1full                 1 3 6 1 4 1 311 89 2 1 7 */
      98,    /* OBJ_p256_picnicl1full            1 3 6 1 4 1 311 89 2 1 8 */
      99,    /* OBJ_rsa3072_picnicl1full         1 3 6 1 4 1 311 89 2 1 9 */
     100,    /* OBJ_picnic3l1                    1 3 6 1 4 1 311 89 2 1 21 */
     101,    /* OBJ_p256_picnic3l1               1 3 6 1 4 1 311 89 2 1 22 */
     102,    /* OBJ_rsa3072_picnic3l1            1 3 6 1 4 1 311 89 2 1 23 */
};
