name: Coding style tests
on: [workflow_call]

jobs:
  check_clang_format:
    name: "Coding style"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: openquantumsafe/ci-ubuntu-latest:latest
    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y clang-format

      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4

      - name: Check coding style using clang-format
        run: ./scripts/do_code_format.sh
