name: Release tests

on:
  workflow_dispatch:
    inputs:
      liboqs_ref:
        description: 'liboqs branch or tag'
        default: 'main'
        type: string

# This workflow can be triggered from either the GitHub Actions web UI or a shell.
# To use a shell, generate a GitHub personal access token and run the following command:
#
# curl --request POST \
#      --header "Accept: application/vnd.github+json" \
#      --header "Authorization: Bearer YOUR_TOKEN_HERE" \
#      --header "X-GitHub-Api-Version: 2022-11-28" \
#      --data '{
#                "ref": "PROVIDER_BRANCH_OR_TAG_HERE",
#                "inputs": {
#                            "liboqs_ref": "LIBOQS_BRANCH_OR_TAG_HERE"
#                          }
#              }' \
#      https://api.github.com/repos/open-quantum-safe/oqs-provider/actions/workflows/liboqs-release.yml/dispatches

jobs:
  release-test:
    uses: ./.github/workflows/release-test.yml
    with:
      liboqs_ref: ${{ inputs.liboqs_ref }}
