name: MacOS tests

on: [pull_request, push]

permissions:
  contents: read

jobs:
  macos:
# Run a job for each of the specified os configs:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-12
          - macos-11
# eventually build for other alg sets, if CCI use is discontinued
        params:
          - oqsconfig: -DOQS_ALGS_ENABLED=STD
    runs-on: ${{matrix.os}}
    env:
# Don't overwhelm github CI VMs:
      MAKE_PARAMS: -j 4
    steps:
      - name: Checkout provider
        uses: actions/checkout@v3
      - name: Checkout openssl
        uses: actions/checkout@v3
        with:
          set-safe-directory: true
          repository: openssl/openssl
          path: openssl
      - name: checkout liboqs
        uses: actions/checkout@v3
        with:
          set-safe-directory: true
          repository: open-quantum-safe/liboqs
          ref: main
          path: liboqs
      - name: Retrieve OpenSSL32 from cache
        id: cache-openssl32
        uses: actions/cache@v3
        with:
          path: .localopenssl32
          key: ${{ runner.os }}-openssl32
      - name: Build openssl3 if not cached
        if: steps.cache-openssl32.outputs.cache-hit != 'true'
        run: pwd && ./config --prefix=`pwd`/../.localopenssl32 && make $MAKE_PARAMS && make install_sw install_ssldirs
        working-directory: openssl
      - name: Save OpenSSL
        id: cache-openssl-save
        if: steps.cache-openssl32.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            .localopenssl32
          key: ${{ runner.os }}-openssl32
      - name: build liboqs
        run: |
           cmake -DOPENSSL_ROOT_DIR=../.localopenssl32 -DCMAKE_INSTALL_PREFIX=../.localliboqs ${{ matrix.params.oqsconfig }} -S . -B build
           cmake --build build
           cmake --install build
        working-directory: liboqs
      - name: build oqs-provider
        run: liboqs_DIR=.localliboqs cmake -DOPENSSL_ROOT_DIR=.localopenssl32 -S . -B build && cmake --build build
      - name: Check Openssl providers
        run: OPENSSL_MODULES=build/lib .localopenssl32/bin/openssl list -providers -provider oqsprovider -provider default
      - name: Run tests
        run: PATH=../.localopenssl32/bin:$PATH ctest -V
        working-directory: build
      # Try brew install of head: If error message below appears, build and test passed successfully
      - name: brew install test
        run: brew install --HEAD --formula -s oqsprovider.rb 2>&1 | grep "Empty installation"
        working-directory: scripts
      - name: Retain oqsprovider.dylib
        uses: actions/upload-artifact@v3
        with:
          name: oqs-provider-${{matrix.os}}-x64
          path: build/lib/oqsprovider.dylib
