name: Release tests

on:
  repository_dispatch:
    types: [ "liboqs-release" ]

jobs:
  release-test:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest

    steps:
      - name: Check if tracker branch exists
        env:
          tracker_branch: ${{ github.event.client_payload.tag }}-tracker
        run: |
          curl --silent \
               --output /dev/null \
               --write-out "\n%{response_code}\n" \
               --request GET \
               --header "Accept: application/vnd.github+json" \
               --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               --header "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/open-quantum-safe/oqs-provider/branches/$tracker_branch | tee curl_out \
            && grep -q "200" curl_out \
            && echo "target_branch=$tracker_branch" >> "$GITHUB_ENV" \
            || echo "target_branch=main" >> "$GITHUB_ENV"
      - name: Checkout oqs-provider on tracker branch if it exists; otherwise, fall back to main
        uses: actions/checkout@v4
        with:
          ref: ${{ env.target_branch }}
      - name: Checkout liboqs at release tag
        uses: actions/checkout@v4
        with:
          repository: open-quantum-safe/liboqs
          path: liboqs
          ref: ${{ github.event.client_payload.tag }}
      - name: Run release tests
        run: ./scripts/release-test.sh
