name: Release tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      liboqs_ref:
        description: 'liboqs branch or tag'
        required: true
        default: 'main'
        type: string
  workflow_dispatch:
    inputs:
      liboqs_ref:
        description: 'liboqs branch or tag'
        required: true
        default: 'main'
        type: string

jobs:
  release-test:
    runs-on: ubuntu-latest
    container:
      image: openquantumsafe/ci-ubuntu-jammy:latest

    steps:
      - name: Checkout oqs-provider
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
      - name: Checkout liboqs
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # pin@v4
        with:
          repository: open-quantum-safe/liboqs
          path: liboqs
          ref: ${{ inputs.liboqs_ref }}
      - name: Run release tests
        run: OPENSSL_BRANCH=master ./scripts/release-test-ci.sh
